# Decline in English Agriculture 1850-1890

## Core

+ [Turner, M. (2004). Agriculture, 1860–1914. In R. Floud & P. Johnson (Eds.), The Cambridge Economic History of Modern Britain (pp. 133-160). Cambridge: Cambridge University Press.](https://doi.org/10.1017/CHOL9780521820370.007){target="_blank"}
+ [FLETCHER, T. W. (1961), THE GREAT DEPRESSION OF ENGLISH AGRICULTURE 1873–1896. The Economic History Review, 13: 417-432.](https://doi.org/10.1111/j.1468-0289.1961.tb02128.x){target="_blank"}
+ [Gráda, Cormac Ó. “Farming High and Low, 1850-1914.” The Agricultural History Review, vol. 49, no. 2, 2001, pp. 210–218.](https://www.jstor.org/stable/40275727){target="_blank"}

## Additional

+ J.D. Chambers and G.E. Mingay, *The Agricultural Revolution 1750-1880* (1966).
+ E.L. Jones, *The Development of English Agriculture 1815-1873* (1968).
+ R. Floud & D. McCloskey (eds), *The Economic History of Britain since 1700* (2nd ed. 1994) vol. II, ch.6 (O’Grada)
+ [P.J. Perry (ed), *British Agriculture 1875-1914* (1973).](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=1539405&ppg=18){target="_blank"}
+ P.J. Perry, British Farming in the Great Depression 1870-1914 (1974).
+ E.T.J. Collins (ed), The Agrarian History of England and Wales 1850-1914 (2002) vol. 7.
+ E.L. Jones, "The Changing Basis of Agricultural Prosperity 1853-1873" *Agricultural History Review* (1962). 
+ S.B. Saul, *The Myth of the Great Depression 1873-1896* (1973)
