# Introduction: key themes and an overview

## Core

+ [Stephen Broadberry, Bruce M. S. Campbell, Alexander Klein, Mark Overton and Bas van Leeuwen, "Prologue: Historical national income accounting", *British Economic Growth, 1270-1870*, CUP: 2015.](https://github.com/gabrielfgm/brit_eh_1700_1940/blob/master/pdfs/broadberry_Prologue_British_Economic_Growth.pdf)
+ [Morgan Kelly, Cormac Ó Gráda, Adam Smith, Watch Prices, and the Industrial Revolution , The Quarterly Journal of Economics, Volume 131, Issue 4, November 2016, Pages 1727–1752](https://doi.org/10.1093/qje/qjw026)

## Additional

+ [William Nordhaus, "Do Real-Output and Real-Wage Measures Capture Reality? The History of Lighting Suggests Not", in R. Gorden and T. Bresnahan (eds.) *The economics of new goods*, Chicago: CUP, 1997.](https://www.nber.org/books-and-chapters/economics-new-goods/do-real-output-and-real-wage-measures-capture-reality-history-lighting-suggests-not)
+ [Diane Coyle, *GDP: A Brief but Affectionate History*, PUP: 2014](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=5695246&ppg=1)
+ [Wrigley, E. (2004). British population during the ‘long’ eighteenth century, 1680–1840. In R. Floud & P. Johnson (Eds.), The Cambridge Economic History of Modern Britain (pp. 57-95). Cambridge: Cambridge University Press.](https://doi.org/10.1017/CHOL9780521820363.004)
+ [Nicholas Crafts, "Forging Ahead and Falling Behind: The Rise and Relative Decline of the First Industrial Nation," *Journal of Economic Perspectives*, Vol. 12, No. 2, 1998.](https://www.jstor.org/stable/2646970)
+ R. Floud & D. McCloskey (eds), *The Economic History of Britain since 1700* (2nd ed. 1994) vol. 1, ch.4 (Schofield)
+ P. Deane, *The First Industrial Revolution* (1965) ch. 2
+ M.W. Flinn, *English Population Growth 1700-1830* (1970)
+ [Gregory Clark, "The condition of the working class in England, 1209-2004," *Journal of Political Economy*, Vol. 113, No. 6, 2005](https://www.journals.uchicago.edu/doi/10.1086/498123)
+ D. McCloskey, "1780-1860: a survey", in R. Floud & D. McCloskey (eds.) *The Economic History of Britain Since 1700*, 2nd Ed. CUP: 1994.
+ [E. A. Wrigley, Chapter 2 "The divergence of England: the growth of the English economy in the seventeenth and eighteenth centuries," in *Poverty, Progress and Population*, CUP: 2004.](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=255180&ppg=60)

## Slides

[Link to view slides](https://gabrielfgm.github.io/beh-slides/01_long_run_overview.html#1). Press `f` to view in full screen and arrows to navigate.
