# The industrious revolution

## Core

+ [Jan de Vries, Ch. 1 "The Transformation of Consumer Desire in the Long Eighteenth Century" in *The Industrious Revolution: Consumer Behavior and the Household Economy, 1650 to the Present*, 2008.](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=347224&ppg=15)
+ [Sara Horrell, Jane Humphries, and Ken Sneath, "Consumption conundrums unravelled," *Economic History Review*, Vol. 68, No. 3, 2015.]( https://doi.org/10.1111/ehr.12084)
+ [Hans-Joachim Voth, "Time and Work in Eighteenth-Century London", *Journal of Economic History*, Vol. 58, no. 1, 1998](https://www.cambridge.org/core/product/identifier/S0022050700019872/type/journal_article)
+ [Koyama, Mark. ‘The Transformation of Labor Supply in the Pre-Industrial World’. Journal of Economic Behavior & Organization 81, no. 2 (2012): 505–23.](https://doi.org/10.1016/j.jebo.2011.07.015)

## Additional

+ [Berg, M. (2004). Consumption in eighteenth- and early nineteenth-century Britain. In R. Floud & P. Johnson (Eds.), The Cambridge Economic History of Modern Britain (pp. 357-387). Cambridge: Cambridge University Press.](https://doi.org/10.1017/CHOL9780521820363.014){target="_blank"}
+ [De Vries, Jan. “The Industrial Revolution and the Industrious Revolution.” The Journal of Economic History, vol. 54, no. 2, 1994, pp. 249–270.](https://www.jstor.org/stable/2123912){target="_blank"}
+ [Berg, M. (2007). *Luxury and Pleasure in Eighteenth-Century Britain.*: Oxford University Press.](https://www.oxfordscholarship.com/view/10.1093/acprof:oso/9780199215287.001.0001/acprof-9780199215287){target="_blank"}
+ McKendrick, Neil, Brewer, John, and Plumb, J. H. *The Birth of a Consumer Society: The Commercialization of Eighteenth-century England.* London: Europa, 1982.
+ [Mark Hailwood, "Time and Work in Rural England, 1500-1700", *Past & Present*, Vol 248, No. 1, 2020](https://doi.org/10.1093/pastj/gtz065)

## Slides

[Link to view slides](https://gabrielfgm.github.io/beh-slides/03_consumption.html#1). Press `f` to view in full screen and arrows to navigate.