# Government and the financial revolution

## Core

+ [Douglass C. North and Barry R. Weingast, "Constitutions and Commitment: The Evolution of Institutions Governing Public Choice in Seventeenth-Century England," *Journal of Economic History*, Vol. 49, No. 4, 1989.](https://www.jstor.org/stable/2122739)
+ [John Brewer, *The Sinews of Power: War, Money and the English State, 1688-1783*, HUP: 1988, Introduction and Ch. 4](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=179738&ppg=11)
+ [Julian Hoppit, "Compulsion, Compensation and Property Rights in Britain, 1688-1833", *Past & Present*, No. 210, 2011](https://academic.oup.com/past/article-lookup/doi/10.1093/pastj/gtq060)

## Additional

+ [Carlos, A., & Neal, L. (2011). Amsterdam and London as financial centers in the eighteenth century. Financial History Review, 18(1), 21-46.](https://doi.org/10.1017/S0968565010000338){target="_blank"}
+ Steven C. A. Pincus and James A. Robinson, "What Really Happened During the Glorious Revolution" in Sebastian Galiani and Itai Sened (eds.) *Institutions, Property Rights, and Economic Growth: The Legacy of Douglass North*, CUP: 2014.
+ [Nathan Sussman and Yishay Yafeh, "Institutional Reforms, Financial Development and Sovereign Debt: Britain 1690-1790," *Journal of Economic History*, Vol. 66, No. 4, 2006.](https://www.jstor.org/stable/4501108){target="_blank"}
+ [Gregory Clark, "The Political Foundations of Modern Economic Growth: England, 1540-1800," *The Journal of Interdisciplinary History,* Vol. 26, No. 4, 1996](https://www.jstor.org/stable/pdf/205042.pdf){target="_blank"}
+ Anne Murphy, *The Origins of English Financial Markets: Investment and Speculation Before the South Sea Bubble*, CUP: 2009.
+ [NEAL, L., & QUINN, S. (2001). "Networks of information, markets, and institutions in the rise of London as a financial centre, 1660–1720." *Financial History Review*, 8(1), 7-26.](https://doi.org/10.1017/S0968565001000130){target="_blank"}

## Slides

[Link to view slides](https://gabrielfgm.github.io/beh-slides/04_gov_finance#1). Press `f` to view in full screen and arrows to navigate.
