# The industrial revolution: an introduction and the factory system

## Core

+ [Maxine Berg, *The Age of Manufactures, 1700-1820* 2nd Edition, Routledge: 1994, Introduction & Ch. 1.](https://keats.kcl.ac.uk/mod/resource/view.php?id=3073196){target="_blank"}
+ [Stephen Marglin, "What do Bosses Do?: The Origins and Functions of Hierarchy in Capitalist Production", *Review of Radical Political Economics*, Vol. 6, No. 2, 1974.](http://journals.sagepub.com/doi/10.1177/048661347400600206)
+ [David S. Landes, "What do Bosses Really Do?", *Journal of Economic History*, Vol. 46, No. 3, 1986](https://www.cambridge.org/core/product/identifier/S0022050700046799/type/journal_article)
+ [Joel Mokyr, "The rise and fall of the factory system: technology, firms, and households since the industrial revolution", *Carnegie-Rochester Conference Series on Public Policy*, Vol. 55, No. 1, 2001](https://linkinghub.elsevier.com/retrieve/pii/S0167223101000501)

## Additional

+ [Julian Hoppit, "Understanding the Industrial Revolution," *Historical Journal*, Vol. 30, No. 1, 1987.]( https://doi.org/10.1017/S0018246X00021993){target="_blank"}
+ [Cannadine, David. “The Present and the Past in the English Industrial Revolution 1880-1980.” Past & Present, no. 103, 1984, pp. 131–172.](https://www.jstor.org/stable/650727){target="_blank"}
+ [Mokyr, J. (2004). Accounting for the Industrial Revolution. In R. Floud & P. Johnson (Eds.), The Cambridge Economic History of Modern Britain (pp. 1-27). Cambridge: Cambridge University Press.](https://doi.org/10.1017/CHOL9780521820363.002){target="_blank"}
+ [Mokyr, J. (2008), *The British Industrial Revolution: An Economic Perspective*, 2nd ed., Chapter 1, Editors Introduction.](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=1717269&ppg=14){target="_blank"}
+ D. Landes, *The Unbound Prometheus* (1969) ch. 2
+ M. Fores, ‘The Myth of a British Industrial Revolution’ *History* (1981)
+ S. Pollard, *Peaceful Conquest: the Industrialisation of Europe 1760-1970* (1981) ch.1
+ R. Hartwell (ed), *The Causes of the Industrial Revolution* (1967) chs. 1 and 2
+ M. Berg & P. Hudson, ‘Rehabilitating the Industrial Revolution’ *Economic History Review* (1992)
+ R. Floud & D. McCloskey (eds), *The Economic History of Britain since 1700* (2nd ed. 1994) vol. I, ch. 3 (Crafts)
+ M. Kirby & M. Rose (eds.), *Business Enterprise in Modern Britain from the Eighteenth to the Twentieth Century* (1994) chs. 2 and 3 (Jones, Rose)
