# Causes of the industrial revolution, I

We begin this week to tackle the large literature on why Britain industrialized,
or at least why Britain industrialized first. We start with Allen's theories
about relative prices and induced technological change read alongside 
some of his critics.

## Core

+ [Robert Allen, "Why the industrial revolution was British: commerce, induced invention, and the scientific revolution," *Economic History Review*, Vol. 64, No. 2, 2011.]( https://doi.org/10.1111/j.1468-0289.2010.00532.x)
+ [Patrick O'Brien, "A conjuncture in global history or an Anglo-American construct: the British Industrial Revolution, 1700–1850," *Journal of Global History*, Vol. 5, No. 3, 2010.]( https://doi.org/10.1017/S1740022810000240)
+ [Jane Humphries, "The lure of aggregates and the pitfalls of the patriarchal perspective: a critique of the high wage economy interpretation of the British industrial revolution," *Economic History Review*, Vol. 66, no. 3, 2013.]( https://doi.org/10.1111/j.1468-0289.2012.00663.x)

## Additional

+ [Nicholas Crafts, "Explaining the first Industrial Revolution: two views," *European Review of Economic History*, Vol. 15, pp. 153-168, 2010.](https://doi.org/10.1017/S1361491610000201)
+ [Stephenson, J. Z. (2018), ‘Real’ wages? Contractors, workers, and pay in London building trades, 1650–1800. *The Economic History Review*, 71: 106-132.]( https://doi.org/10.1111/ehr.12491) 
+ [Allen, R. C. (2019), Real wages once more: a response to Judy Stephenson. *The Economic History Review*, 72: 738-754.](https://doi.org/10.1111/ehr.12663){target="_blank"}
+ [Humphries, J. and Schneider, B. (2019), Spinning the industrial revolution. *The Economic History Review*, 72: 126-155.](https://doi.org/10.1111/ehr.12693)
+ [Allen, R. C. (2019), Spinning their wheels: a reply to Jane Humphries and Benjamin Schneider. *The Economic History Review*.](https://doi.org/10.1111/ehr.12850)

## Slides

[Link to view slides](https://gabrielfgm.github.io/beh-slides/06_causes_IR.html#1). Press `f` to view in full screen and arrows to navigate.