# The industrial revolution and international trade

## Core

+ [Ronald Findlay and Kevin O'Rourke, Chapter 6 "Trade and the Industrial Revolution" in *Power and Plenty: Trade, War, and the World Economy in the Second Millenium*, PUP: 2007.](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=485770&ppg=340)
+ [Joseph Inikori, Chapter 3 "A Historiography of the first industrial revolution" in *Africans and the Industrial Revolution*, CUP: 2002.](https://hdl.handle.net/2027/heb.02605)
+ [Nuala Zahedieh, "Eric Williams and William Forbes: copper, colonial markets, and commercial capitalism", *The Economic History Review*, Vol. 74, No. 3, p. 784-808](https://doi.org/10.1111/ehr.13050)

## Additional

+ [Harley, C. (2004). Trade: Discovery, mercantilism and technology. In R. Floud & P. Johnson (Eds.), The Cambridge Economic History of Modern Britain (pp. 175-203). Cambridge: Cambridge University Press.](https://doi.org/10.1017/CHOL9780521820363.008) {target="_blank"}
+ [Engerman, S., & O’Brien, P. (2004). The industrial revolution in global perspective. In R. Floud & P. Johnson (Eds.), The Cambridge Economic History of Modern Britain (pp. 451-464). Cambridge: Cambridge University Press.](https://doi.org/10.1017/CHOL9780521820363.017){target="_blank"}
+ J. Price, ‘What did Merchants Do? Reflections on British Overseas Trade 1660-1790’ *Journal of Economic History* (1989)
+ D. Barnett, *London: Hub of the Industrial Revolution* (1998) Introduction and ch. 6
+ S. Chapman, *Merchant Enterprise in Britain from the Industrial Revolution to World War 1* (1992) ch.3

## Slides

[Link to view slides](https://gabrielfgm.github.io/beh-slides/07_trade_ir.html#1). Press `f` to view in full screen and arrows to navigate.