# Causes of the Industrial Revolution, II

We continue our study this week of the causes of the industrial revolution.
Our focus this week is on Mokyr and critics of his work. Mokyr puts 
much greater emphasis on innovation, knowledge and culture, and focuses more
on domestic determinants of industrialization, with his critics often
pointing to international connections.

## Core

+ [Joel Mokyr, "'The Holy Land of Industrialism': rethinking the Industrial Revolution", *Journal of the British Academy*, Vol. 9, 2021](https://www.thebritishacademy.ac.uk/publishing/journal-british-academy/9/the-holy-land-of-industrialism-rethinking-the-industrial-revolution/)
+ [Nuala Zahedieh, "Britain's Atlantic slave economy, the market for knowledge and skills, and early industrialisation: a response to Joel Mokyr's 'Holy Land of Industrialism'", *Journal of the British Academy*, Vol. 9, 2021](https://www.thebritishacademy.ac.uk/publishing/journal-british-academy/9/britains-atlantic-slave-economy-market-knowledge-early-industrialisation/)
+ [Maxine Berg & Pat Hudson, "Slavery, Atlantic trade and skills: a response to Mokyr's 'Holy Land of Industrialism'", *Journal of the British Academy*, Vol. 9, 2021](https://www.thebritishacademy.ac.uk/publishing/journal-british-academy/9/slavery-atlantic-trade-skills/)

## Additional

+ Joel Mokyr, *The Enlightened Economy: An Economic History of Britain 1700-1850*, Yale: 2009, Introduction and Chapter 5. 
+ [Morgan Kelly, Joel Mokyr, and Cormac O Grada, "Precocious Albion: A New Interpretation of the British Industrial Revolution," *Annual Review of Economics*, Vol. 6, 2014.](https://www.annualreviews.org/doi/abs/10.1146/annurev-economics-080213-041042)
+ [Marxine Berg, "Useful knowledge, 'industrial enlightenment', and the place of India", *Journal of Global History*, Vol. 8, No. 1, 2013.](https://www.cambridge.org/core/product/identifier/S1740022813000077/type/journal_article)
+ [Joel Mokyr, "Bottom-up or Top-down? The origins of the Industrial Revolution", *Journal of Institutional Economics*, Vol. 14, No. 6, 2018](https://www.cambridge.org/core/product/identifier/S174413741700042X/type/journal_article)

