# 19th century globalization and trade

The enormous growth in industrial capacity in the 19th century had 
global consequences. Within Britain, the political equilibrium moved
towards the full embrace of free trade. Globally, industrial technologies
such as steam were pushing down transportation costs driving the integration
of global markets. The result was a sharp growth in global trade and 
the convergence of global commodity prices which resulted in both
improved purchasing power for British labor, and declining profitability
for the British agricultural sector.

## Core

+ [Kevin O'Rourke and Jeffrey Williamson, *Globalization and History: The Evolution of a Nineteenth-Century Atlantic Economy*, MIT: 1996, Chapters 2, 3 & 5.](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=3338827&ppg=18)
+ [Turner, M. (2004). Agriculture, 1860–1914. In R. Floud & P. Johnson (Eds.), The Cambridge Economic History of Modern Britain (pp. 133-160). Cambridge: Cambridge University Press.](https://doi.org/10.1017/CHOL9780521820370.007){target="_blank"}
+ [Cheryl Schonhardt-Bailey, *From the Corn Laws to Free Trade: Interests, Ideas and Institutions in Historical Perspective*, MIT: 2006, Chapter 1.](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=3338560&ppg=16)

## Additional

+ [C. Knick Harley, "Ocean Freight Rates and Productivity, 1740-1913: The Primacy of Mechanical Invention Reaffirmed," *Journal of Economic History*, Vol. 48, No. 4, 1988.](https://www.jstor.org/stable/2121620)
+ [FLETCHER, T. W. (1961), THE GREAT DEPRESSION OF ENGLISH AGRICULTURE 1873–1896. The Economic History Review, 13: 417-432.](https://doi.org/10.1111/j.1468-0289.1961.tb02128.x){target="_blank"}
+ [Gráda, Cormac Ó. “Farming High and Low, 1850-1914.” The Agricultural History Review, vol. 49, no. 2, 2001, pp. 210–218.](https://www.jstor.org/stable/40275727){target="_blank"}
+ [O'Rourke, Kevin H., et al. "Factor Price Convergence in the Late Nineteenth Century". *International Economic Review*, vol. 37, no. 3, 1996, pp. 499–530.](https://www.jstor.org/stable/2527439){target="_blank"}
+ [O'Rourke, Kevin H. “The European Grain Invasion, 1870-1913.” *The Journal of Economic History*, vol. 57, no. 4, 1997, pp. 775–801.](https://www.jstor.org/stable/2951160){target="_blank"}
+ [Yrjo Kaukiainen, "Shrinking the world: Improvements in the speed of information transmission, c. 1820-1870," *European Review of Economic History*, Vol. 5, 2001, pp. 1-28.](https://doi.org/10.1017/S1361491601000016){target="_blank"}
+ [Henry Miller, "Popular Petitioning and the Corn Laws, 1833-46", *English Historical Review*, Vol. CXXVII, No. 527, 2012.](
https://www.jstor.org/stable/23272690)
+ J D Chambers & G E Mingay, *The Agricultural Revolution, 1750-1880*, Batsford: London, 1966, Ch. 6.
+ Anthony Howe, *Free Trade and Liberal England 1846–1946*, OUP: 1998, chapter 1.
+ J.D. Chambers and G.E. Mingay, *The Agricultural Revolution 1750-1880* (1966).
+ E.L. Jones, *The Development of English Agriculture 1815-1873* (1968).
+ R. Floud & D. McCloskey (eds), *The Economic History of Britain since 1700* (2nd ed. 1994) vol. II, ch.6 (O’Grada)
+ [P.J. Perry (ed), *British Agriculture 1875-1914* (1973).](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=1539405&ppg=18){target="_blank"}
+ P.J. Perry, British Farming in the Great Depression 1870-1914 (1974).
+ E.T.J. Collins (ed), The Agrarian History of England and Wales 1850-1914 (2002) vol. 7.
+ E.L. Jones, "The Changing Basis of Agricultural Prosperity 1853-1873" *Agricultural History Review* (1962). 
+ S.B. Saul, *The Myth of the Great Depression 1873-1896* (1973)

## Slides

[Link to view slides](https://gabrielfgm.github.io/beh-slides/10_grain_invasion). Press `f` to view in full screen and arrows to navigate.

[Link to view slides](https://gabrielfgm.github.io/beh-slides/13_great_depression.html#1). Press `f` to view in full screen and arrows to navigate.