# British banking and the money market

In this week we turn to considering the financial economy. We focus here
on the development of banking, starting with the origins of the Bank of
England and surveying the evolution of private banking as well. We 
also spend some time considering the money market -- the market for
borrowing money -- which in the 19th century was strongly centered
on London. Building on last week's discussion of trade, we see the pivotal
role of the London money market in financing global trade.

## Core

+ [Charles W. Calomiris & Stephen H. Haber, *Fragile by Design: The Political Origins of Banking Crises & Scarce Credit*, Princeton University Press, 2014, Chs. 4 & 5](https://ebookcentral.proquest.com/lib/kcl/detail.action?docID=1561556)
+ [Turner, J. (2014). "The evolution of British banking structure and stability since 1800." In *Banking in Crisis: The Rise and Fall of British Banking Stability*, 1800 to the Present. Cambridge: Cambridge University Press.](https://librarysearch.kcl.ac.uk/permalink/f/1scv9r3/44KCL_ALEPH_DS001654593)
+ [Walter Bagehot, Lombard Street (Richard D. Irwin, Inc., 1873). Chs 1 & 2.](https://hdl.handle.net/2027/mdp.39015035108102)
+ [Olivier Accominotti, Delio Lucena-Piquero, and Stefano Ugolini, “The origination and distribution of money market instruments,” The Economic History Review (November 2021), 74: 4, 892–921](https://doi.org/10.1111/ehr.13049)

## Additional

+ [BIGNON, V. , FLANDREAU, M. and UGOLINI, S. (2012), Bagehot for beginners: the making of lender‐of‐last‐resort operations in the mid‐nineteenth century1. *The Economic History Review*, 65: 580-608.](https://doi.org/10.1111/j.1468-0289.2011.00606.x)
+ [Patrick K. O'Brien & Nuno Palma, "Not an ordinary bank but a great engine of state: the Bank of England and the British economy, 1694-1844", *Economic History Review*, 2022](https://doi.org/10.1111/ehr.13191)
+ [Richard Grossman, *Unsettled Account : The Evolution of Banking in the Industrialized World since 1800*, Princeton University Press, 2010, Ch. 7 "Banking Evolution in England"](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=539798&ppg=192)
+ [Forrest Capie, "British Financial Crises in the Nineteenth and Twentieth Centuries" in Nicholas Dimsdale and Anthony Hotson (eds.) *British Financial Crises since 1825*, OUP: 2014.](https://www.oxfordscholarship.com/view/10.1093/acprof:oso/9780199688661.001.0001/acprof-9780199688661-chapter-2){target="_blank"}

### On the gold standard if interested

+ [Redish, Angela. “The Evolution of the Gold Standard in England.” *The Journal of Economic History*, vol. 50, no. 4, 1990, pp. 789–805.](https://www.jstor.org/stable/2122455){target="_blank"}
+ [Flandreau, M. (1996). The French Crime of 1873: An Essay on the Emergence of the International Gold Standard, 1870–1880. *The Journal of Economic History*, 56(4), 862-897.](https://doi:10.1017/S0022050700017502){target="_blank"}
+ [Sargent, Thomas J., and François R. Velde. *The Big Problem of Small Change*, Princeton University Press, 2003. Chs. 1, 16 & 17](https://ebookcentral.proquest.com/lib/kcl/detail.action?docID=1651876){target="_blank"}

## Slides

[Link to view slides](https://gabrielfgm.github.io/beh-slides/11_boe_money_finance#1). Press `f` to view in full screen and arrows to navigate.

