# Entrepreneurial Failure?

## Core

+ [D. McCloskey and Lars G. Sandberg, "From damnation to redemption: Judgments on the late victorian entrepreneur," *Explorations in Economic History*, Vol. 9, 1971–1972, Pages 89-108.](https://www.sciencedirect.com/science/article/abs/pii/0014498371900520?via%3Dihub){target="_blank"}
+ [Elbaum, Bernard, and William Lazonick. “The Decline of the British Economy: An Institutional Perspective.” The Journal of Economic History, vol. 44, no. 2, 1984, pp. 567–583.](https://www.jstor.org/stable/2120731){target="_blank"}
+ [Leunig, Timothy. “A British Industrial Success: Productivity in the Lancashire and New England Cotton Spinning Industries a Century Ago.” *The Economic History Review*, vol. 56, no. 1, 2003, pp. 90–117.](https://www.jstor.org/stable/3698755){target="_blank"}

## Additional

+ [Nicholas, T. (2004). Enterprise and management. In R. Floud & P. Johnson (Eds.), The Cambridge Economic History of Modern Britain (pp. 227-252). Cambridge: Cambridge University Press.](https://doi.org/10.1017/CHOL9780521820370.010){target="_blank"}
+ D.C. Coleman & C. MacLeod, ‘Attitudes to New Techniques: British Businessmen 1800-1950’ *Economic History Review* (1986)
+ M.J. Wiener, *English Culture and the Decline of the Industrial Spirit 1850-1980* (1981) chs. 1 - 4
+ P.L. Payne, *British Entrepreneurship in the Nineteenth Century* (1974)
+ R. Floud & D. McCloskey (eds), *The Economic History of Britain since 1700* (2nd ed. 1994) vol. II, ch. 3 (Pollard)
+ A Godley, ‘Entrepreneurship in Victorian Britain’ in D. Landes, W. Baumol & J. Mokyr (eds), *The Invention of Enterprise* (2009). 
+ Ciliberto (2010) “Were British cotton entrepreneurs technologically backward? Firm-level evidence on the adoption of ring spinning” Explorations in Economic History
+ Broadberry and Marrison (2002) "External Economies of Scale in the Lancashire Cotton Industry, 1900-1950" Economic History Review
+ Broadberry (1998) “How did the United States and Germany Overtake Britain? A Sectoral Analysis of Comparative Productivity Levels, 1870-1990” Journal of Economic History

## Slides

[Link to view slides](https://gabrielfgm.github.io/beh-slides/15_entrepreneurial#1). Press `f` to view in full screen and arrows to navigate.
