# Empire and capital market integration

We turn this week to a consideration of international finance and empire. 
Economic historians determined that a stylized fact about international
capital markets is that British colonies enjoyed lower borrowing costs. This
led to some substantial debate about why this was the case, and what it tells
us about colonial policies.

## Core

+ [Ferguson, N., and M. Schularick (2006), “The Empire Effect: The Determinants of Country Risk in the First Age of Globalization, 1880–1913.” Journal of Economic History, vol. 66, pp. 283-312.](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/09D7C8C5A22F519A80522C8AB9527686/S002205070600012Xa.pdf/empire_effect_the_determinants_of_country_risk_in_the_first_age_of_globalization_18801913.pdf)
+ [Accominotti, O., M. Flandreau and R. Rezzik, (2011), “The Spread of Empire: Clio and the Measurement of Colonial Borrowing Costs", The Economic History Review, vol. 64, pp. 385-407.](https://www.jstor.org/stable/41262429)
+ [Gardner, L. (2017): Colonialism or supersanctions: sovereignty and debt in West Africa, 1871-1914, in: *European Review of Economic History*, 21, 236-257.](https://doi.org/10.1093/ereh/hex001)

## Additional

+ [Accominotti et al. "Black man's burden, white man's welfare: control, devolution and development in the British Empire, 1880-1914", *European Review of Economic History*, Vol. 14, No. 1, 2010](https://academic.oup.com/ereh/article-lookup/doi/10.1017/S1361491609990025)
+ [Offer, Avner. “The British Empire, 1870-1914: A Waste of Money?” *The Economic History Review*, vol. 46, no. 2, 1993, pp. 215–238.](https://www.jstor.org/stable/2598015)
+ [Cain, P. (1998). Was it Worth Having? the British Empire 1850–1950. Revista De Historia Económica / Journal of Iberian and Latin American Economic History, 16(1), 351-376.](https://github.com/gabrielfgm/ma_econ_history/blob/main/cain1998.pdf)
+ Davis & Huttenback, *Mammon and the Pursuit of Empire*
+ Michael Edelstein, "Imperialism: cost and benefit," in Floud & McCloskey (eds) *The Economic History of Britain since 1700*, Vol. 2, 1994.
+ CAIN,  P.  J.,   and   HOPKINS,   A.  G.   (1993a):  *British  Imperialism:  Innovation and Expansion,  1688-1914*,  London.
+ [Bordo and Rockoff (1996) "The Gold Standard as a “Good Housekeeping Seal of Approval”" The Journal of Economic History](
  https://www.jstor.org/stable/2123971)
+ [Bordo, M., and F. Kydland (1995), "The Gold Standard As a Rule: An Essay in Exploration." Explorations in Economic History, vol. 32, pp. 423-464.](https://www.sciencedirect.com/science/article/pii/S0014498385710194)
+ [Obstfeld, M., and A. Taylor (2002), “Globalization and Capital Markets”, NBER Working Paper No 8846.](https://www.nber.org/system/files/working_papers/w8846/w8846.pdf)
+ [Flandreau M., and F. Zumer (2004), *The Making of Global Finance, 1880-1913*, OECD: Development Centre.](https://www.oecd-ilibrary.org/docserver/9789264015364-en.pdf?expires=1642680086&id=id&accname=oid008858&checksum=3B491BE7F7259024B9D115FA9E65EECD)
+ [Offer, Avner. “The British Empire, 1870-1914: A Waste of Money?” *The Economic History Review*, vol. 46, no. 2, 1993, pp. 215–238.](https://www.jstor.org/stable/2598015){target="_blank"}
+ [Cain, P. (1998). Was it Worth Having? the British Empire 1850–1950. Revista De Historia Económica / Journal of Iberian and Latin American Economic History, 16(1), 351-376.](https://keats.kcl.ac.uk/mod/resource/view.php?id=3064713){target="_blank"}
+ Michael Edelstein, "Imperialism: cost and benefit," in Floud & McCloskey (eds) *The Economic History of Britain since 1700*, Vol. 2, 1994.
+ CAIN,  P.  J.,   and   HOPKINS,   A.  G.   (1993a):  *British  Imperialism:  Innovation and Expansion,  1688-1914*,  London.
+ Davis & Huttenback, *Mammon and the Pursuit of Empire*.
+ [Patrick O'Brien, "The Costs and Benefits of British Imperialism, 1846-1914", *Past & Present*, Vol. 120, No. 1, 1988](https://academic.oup.com/past/article-lookup/doi/10.1093/past/120.1.163)

## Slides

[Link to view slides](https://gabrielfgm.github.io/beh-slides/16_imperialism#1). Press `f` to view in full screen and arrows to navigate.
