# Unemployment assistance, the labour market and trade

## Core

+ [George Boyer, *The Winding Road to the Welfare State: Economic Insecurity and Social Welfare Policy in Britain*, PUP: 2019, chapters 3 & 6.](https://ebookcentral.proquest.com/lib/kcl/detail.action?docID=5528405)
+ [Huberman, Michael, and Christopher M. Meissner. “Riding the Wave of Trade: The Rise of Labor Regulation in the Golden Age of Globalization.” *Journal of Economic History* 70, no. 3 (2010): 657–85.](https://www.jstor.org/stable/40836583 ){target="_blank"}

## Additional

+ [Boyer, G. (2004). Living standards, 1860–1939. In R. Floud & P. Johnson (Eds.), The Cambridge Economic History of Modern Britain (pp. 280-313). Cambridge: Cambridge University Press.](https://doi.org/10.1017/CHOL9780521820370.012){target="_blank"}
+ [Hatton, T. (2004). Unemployment and the labour market, 1870–1939. In R. Floud & P. Johnson (Eds.), The Cambridge Economic History of Modern Britain (pp. 344-373). Cambridge: Cambridge University Press.]( https://doi.org/10.1017/CHOL9780521820370.014) {target="_blank"}
+ Huberman, Michael. *Odd Couple: International Trade and Labor Standards in History.* New Haven, CT: Yale University Press, 2012.
