# The economics of WWI

## Core

+ [Avner Offer, Chapter 1 "Introduction: Economic and Social Interpretation of the First World War" *The First World War: an agrarian interpretation*, OUP: 1989](https://hdl.handle.net/2027/heb.03445){target="_blank"}
+ [Stephen broadberry & Peter Howlett, "The United Kingdom during World War I: business as usual?" in S. Broadberry and M. Harrison (eds.), *The Economics of World War I*, CUP: 2005.](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=241098&ppg=224){target="_blank"}

## Additional

+ W, Ashworth, *An Economic History of England 1870-1939* (1960) ch.12
+ S. Pollard, *The Development of the British Economy 1914-1980* (1970) ch. 2
+ D.H. Aldcroft & H. Richardson (eds), *The British Economy 1870-1939* (1969) Section B, ch. 6
+ A.S. Milward, *The Economic Effects of the World Wars on Britain* (1970)
+ B.W. Alford, *Depression and Recovery? British Economic Growth 1918-1939* (1972)
+ Rowe, David M. “The Tragedy of Liberalism: How Globalization Caused the First World War.” *Security Studies* 14, no. 3 (2005): 407–47.
+ Tooze, Adam, and Ted Fertik. “The World Economy and the Great War.” *Geschichte und Gesellschaft* 40, no. 2 (2014): 214–38.

## Slides

[Link to view slides](https://gabrielfgm.github.io/beh-slides/18_wwi#1). Press `f` to view in full screen and arrows to navigate.
