# Globalization and WWI

We consider this week the role of the economic changes we have been discussing
in the coming of WWI. We also consider the disruption of the war to the 
financial and trading networks we have been discussing in the last few 
weeks. 

## Core

+ [Avner Offer, Chapter 1 "Introduction: Economic and Social Interpretation of the First World War" *The First World War: an agrarian interpretation*, OUP: 1989](https://hdl.handle.net/2027/heb.03445){target="_blank"}
+ [Adam Tooze, Ted Fertik, "The World Economy and the Great War", *Geschichte und Gesellschaft*, Vol. 40, 2014](https://www.vr-elibrary.de/doi/10.13109/gege.2014.40.2.214)
+ Kevin O'Rourke, "Economic History and Contemporary Challenges to Globalization", *Journal of Economic History*, Vol. 79, No. 2, 2019.
+ [J. M. Keynes, “War and the Financial System, August, 1914,” The Economic Journal (September 1914), 24: 95, 460–486.](https://doi.org/10.2307/2222023)

## Additional

+ [Stephen broadberry & Peter Howlett, "The United Kingdom during World War I: business as usual?" in S. Broadberry and M. Harrison (eds.), *The Economics of World War I*, CUP: 2005.](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=241098&ppg=224){target="_blank"}
+ W, Ashworth, *An Economic History of England 1870-1939* (1960) ch.12
+ S. Pollard, *The Development of the British Economy 1914-1980* (1970) ch. 2
+ D.H. Aldcroft & H. Richardson (eds), *The British Economy 1870-1939* (1969) Section B, ch. 6
+ A.S. Milward, *The Economic Effects of the World Wars on Britain* (1970)
+ B.W. Alford, *Depression and Recovery? British Economic Growth 1918-1939* (1972)
+ Rowe, David M. “The Tragedy of Liberalism: How Globalization Caused the First World War.” *Security Studies* 14, no. 3 (2005): 407–47.
+ [Jamie Martin, "Globalizing the History of the First World War: Economic Approaches", *Historical Journal*, 2021](https://www.cambridge.org/core/product/identifier/S0018246X21000765/type/journal_article)
+ [Thomas Hauner, Branko Milanovic and Suresh Naidu, "Inequality, Foreign Investment, and Imperialism Prior to World War I", Working Paper, February 2020](https://stonecenter.gc.cuny.edu/files/2017/11/milanovic-inequality-foreign-investment-and-imperialism-2020.pdf)

## Slides

[Link to view slides](https://gabrielfgm.github.io/beh-slides/18_wwi#1). Press `f` to view in full screen and arrows to navigate.
