# Interwar financial and monetary crisis

This week, we begin to tackle the breakdown of the international system in
the interwar period. In particular, we take on the extended debate on why 
the great depression was so severe and extended. This draws on scholarship 
by Kindleberger and Eichengreen who have pointed in different ways to defects
in the international monetary system, and the pathologies of the gold 
standard in the interwar period. This has led to debate on the role of 
central bank cooperation vs Bank of England leadership. We will tackle
these debates as well as cover the departure of Britain from the gold standard
in 1931.

## Core

+ [Charles Kindleberger, *The World in Depression, 1929-1939*, Ch. 14](https://keats.kcl.ac.uk/pluginfile.php/4676786/mod_resource/content/0/kindleberger_ch14.pdf)
+ [Marc Flandreau, ‘Central Bank Cooperation in Historical Perspective: a Sceptical View’, *The Economic History Review*, 2nd ser., 50:4 (November 1997), 735-63.](https://www.jstor.org/stable/2599884)
+ [Barry Eichengreen, *Golden Fetters: The Gold Standard and the Great Depression, 1919-1939*, OUP: 1996, Chapter 7 "The Interwar Gold Standard in Operation"](https://www.oxfordscholarship.com/view/10.1093/0195101138.001.0001/acprof-9780195101133-chapter-7){target="_blank"}
+ [Accominotti, Olivier. “London Merchant Banks, the Central European Panic, and the Sterling Crisis of 1931.” The Journal of Economic History, vol. 72, no. 1, 2012, pp. 1–43.](https://www.jstor.org/stable/41353822){target="_blank"}

## Additional

+ [Barry Eichengreen, Chapter 3 "Interwar Instability" *Globalizing Capital: A History of the International Monetary System*, PUP: 2008.](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=483542&ppg=48){target="_blank"}
+ [Accominotti, O. (2019), International banking and transmission of the 1931 financial crisis. *The Economic History Review*, 72: 260-285.](https://doi.org/10.1111/ehr.12736){target="_blank"}
+ Adam Tooze, *The Deluge: The Great War, America and the Remaking of the Global Order, 1916-1931*, 2014, Chapter 19 "The Great Deflation"
+ [Accominotti, O. and Eichengreen, B. (2016), "The mother of all sudden stops: capital flows and reversals in Europe, 1919–32". *The Economic History Review*, 69: 469-492.]( https://doi.org/10.1111/ehr.12128){target="_blank"}


## Slides

[Link to view slides](https://gabrielfgm.github.io/beh-slides/19_interwar_finance.html#1). Press `f` to view in full screen and arrows to navigate.

