---
title: "British Economic History Syllabus"
author: "Dr. Gabriel Geisler Mesevage"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
documentclass: book
output_dir: "docs"
output:
  bookdown::gitbook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(bookdown)
```

# Class Description {-}

The growth, transformation and fluctuation of economies do much to determine the structures of societies and their polities. Because the transformation of Britain’s economy after 1700 had repercussions both nationally and internationally, this course will touch upon global developments as well as the remarkable growth of the world’s first industrial nation. Within the span of a generation, industrial production superseded agriculture as the mainstay of British prosperity and much of the population came to inhabit large towns instead of the traditional rural village. The Industrial revolution, the success and decline of English farming, the altering character of the workplace, the origins of foreign competition, the dominance of London in international finance, the effects of the Great War and the inter-war slump are all studied. How the British economy adapted both to events in the world beyond and to shifts within Britain’s own population forms an essential theme throughout. There are many historical debates regarding Britain’s economic performance, both successes and failures, within the period 1700 to 1939 – an appreciation of all of which will be required.

# Background Reading & Archival Sources {-}

## General economics

+ Robert Allen, *Global Economic History: a very short introduction*, OUP: 2011. Allen is a prolific economic historian whose work we will encounter throughout the course, and this is a remarkably concise introduction to a very large topic.
+ [Partha Dasgupta, *Economics: a very short introduction*, OUP: 2007.](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=415258&ppg=2) This is a very well-reviewed brief introduction.
+ [Steven Durlauf & Lawrence Blume, *The New Palgrave Dictionary of Economics*.](https://link.springer.com/referencework/10.1057/978-1-349-95121-5#editorsandaffiliations) A helpful reference for looking up economic ideas you are unfamiliar with.

## General surveys for the course

+ [Floud, R., & Johnson, P. (Eds.). (2004). *The Cambridge Economic History of Modern Britain.* Cambridge: Cambridge University Press.](https://www.cambridge.org/core/books/cambridge-economic-history-of-modern-britain/CE91402967901B6BF90415B4D73FC79B) This is the first edition of the CEHMB which is available in digital form via the library. A newer edition exists. The link is to the first volume but all three volumes are available.
+ R. Floud and D. McCloskey (Eds.). (1994). *The Economic History of Britain since 1700.* 3 vols. Cambridge: Cambridge University Press. This is another 3 volume survey of British economic history since 1700. It is quite similar to the newer editions but contains some articles that are not covered by the newer surveys.

## Data sources

+ [Federal Reserve Economic Data (FRED)](https://fred.stlouisfed.org/) contains an enormous number of series. Most data is contemporary but they have some series that are historical.
+ [Jordà-Schularick-Taylor Macrohistory Database](http://www.macrohistory.net/data/) is developed by economic historians and contains macroeconomic data.
+ [http://eh.net/](http://eh.net/) is run by the Economic History Association and posts a number of published data series on its website. It also maintains [MeasuringWorth](https://www.measuringworth.com/datasets.html) for historical value comparisons.
